### ISSUE TITLE
preprocess.py中函数ct_reorient中有两行代码顺序反了

### ISSUE THREAD

**Issue by Ri-Yue-Shui-Hua** [ShanghaiTech-IMPACT/Multi-View-Vertebra-Localization-and-Identification-from-CT-Images#2]
`arr = nio.apply_orientation(arr, ornt_trans)
aff_trans = nio.inv_ornt_aff(ornt_trans, arr.shape)
    `
应改成
`aff_trans = nio.inv_ornt_aff(ornt_trans, arr.shape)
    arr = nio.apply_orientation(arr, ornt_trans)`

**Comment by Fitz-Fitz** [comment]
Hi, thank you for your attention to our work.
Here considering the function of ct_reorient, I think the original order seems to be the correct one.
I understand your concern that the arr.shape may change after applying the orientation transformation. But if we switch the order, we will end up calculating the inverse orientation affine transformation based on the original shape of arr, not its shape after the orientation change.
